name: CI Test & Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List files (debug)
        run: ls -la

      - name: Extract offline node modules bundle
        run: |
          if [ -f offline-node-modules.tar.gz ]; then
            echo "Bundle found. Extracting..."
            tar -xzf offline-node-modules.tar.gz
          else
            echo "ERROR: offline-node-modules.tar.gz not found in working directory."
            exit 1
          fi

      - name: Run tests
        run: npm test
