name: Offline Codex Audit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract dependencies
        run: tar -xzf offline-node-modules.tar.gz

      - name: Run lint
        run: npx eslint .

      - name: Run tests
        run: npx jest --ci
